config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [] do
    get 'profile', on: :member
  end
  resources :sale_posts, only: [:show, :new, :create, :edit, :destroy, :update] do
    resources :orders, only: [:create]
    resources :questions, only: [:create] do
      resources :answers, only: [:create]
    end
    post 'disable', on: :member
    post 'enable', on: :member
    get 'search', on: :collection
  end
  resources :categories, only: [:show]
  resources :orders, only: [:show] do
    resources :messages, only: [:create]
    member do
      post 'complete'
      post 'cancel'
    end
  end
  resources :notifications, only: [] do
    post 'seen'
  end
  resource :my_account, controller: :my_account, only: [:show] do
    get :history, on: :member
    get :sale_posts, on: :member
  end
  resource :dashboard, controller: :dashboard, only: [:show] do
    resources :companies, only: [:show, :new, :create] do
      resources :categories, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :company, only: [] do
        resources :sale_posts, only: [:index]
      end
    end
  end

  root to: 'home#index'
end

app/models/sale_post.rb
class SalePost < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :orders, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_one_attached :cover

  enum status: { enabled: 0, disabled: 10, sold: 20 }

  validates :title, :description, :price, presence: true
end

app/controllers/api/v1/sale_posts_controller.rb
module Api
  module V1
    class SalePostsController < ApiController
      def index
        company = Company.find(params[:company_id])
        render json: company.sale_posts.enabled.to_json
      end
    end
  end
end

app/controllers/sale_posts_controller.rb
class SalePostsController < ApplicationController
  before_action :user_must_be_enabled, only: [:new, :create]
  before_action :user_must_be_the_author, only: [:edit, :update, :destroy]
  before_action :user_must_be_seller_if_post_is_not_enabled, only: [:show]

  def show
    @order_in_progress = current_user.buying_order_in_progress_at_sale_post(@sale_post)
    @questions = @sale_post.questions.includes([:user, :answer])
    @question = Question.new
    @answer = Answer.new
  end

  def new
    @sale_post = SalePost.new
    @categories = Category.where(company_id: current_user.company_id)
    return unless @categories.empty?

    redirect_to root_path, alert: 'Não há categorias cadastradas na sua empresa. Contate o administrador'
  end

  def create
    @sale_post = SalePost.new(sale_post_params)
    @categories = current_user.company.categories.order(name: :asc)

    if @categories.empty?
      flash[:alert] = 'Não há categorias cadastradas na sua empresa. Contate o administrador'
      return redirect_to root_path
    end

    @sale_post.save ? redirect_to(@sale_post, notice: 'Anúncio criado com sucesso') : render(:new)
  end

  def edit
    @categories = current_user.company.categories.order(name: :asc)
  end

  def update
    if @sale_post.update(sale_post_params)
      redirect_to @sale_post, notice: 'Anúncio atualizado com sucesso'
    else
      render :edit
    end
  end

  def search
    @keyword = params[:q]
    @posts = SalePost.where(
      'title LIKE ? OR description LIKE ? AND status = ?', "%#{@keyword}%", "%#{@keyword}%", SalePost.statuses[:enabled]
    )
  end

  def enable
    @post = SalePost.find(params[:id])

    return redirect_to sale_post_path(@post) if current_user != @post.user

    @post.enabled!
    redirect_to @post, notice: 'Anúncio reativado com sucesso'
  end

  def disable
    @post = SalePost.find(params[:id])

    return redirect_to sale_post_path(@post) if current_user != @post.user

    unless @post.orders.in_progress.empty?
      flash[:alert] = 'Este anúncio possui pedidos de compra pendentes. Finalize-os primeiro e tente novamente'
      return redirect_to sale_post_path(@post)
    end

    @post.disabled!
    redirect_to sale_post_path(@post), notice: 'Anúncio desativado com sucesso'
  end

  def destroy
    unless @sale_post.orders.empty?
      flash[:alert] = 'Falha ao excluir anúncio. Este anúncio possui pedidos de compra'
      return redirect_to sale_post_path(@sale_post)
    end

    if @sale_post.destroy
      redirect_to root_path, notice: 'Anúncio excluído com sucesso'
    else
      redirect_to sale_post_path(@sale_post), 'Falha ao excluir anúncio. Tente novamente mais tarde'
    end
  end

  private

  def sale_post_params
    params
      .require(:sale_post)
      .permit(:title, :description, :price, :category_id, :cover)
      .merge(user_id: current_user.id)
  end

  def user_must_be_enabled
    return if current_user.enabled?

    redirect_to root_path, alert: 'Para criar um anúncio seu perfil deve estar preenchido'
  end

  def user_must_be_the_author
    @sale_post = SalePost.find(params[:id])
    return redirect_to root_path, alert: 'Acesso negado' unless @sale_post.user == current_user
  end

  def user_must_be_seller_if_post_is_not_enabled
    @sale_post = SalePost.find(params[:id])
    redirect_to root_path, alert: 'Anúncio indisponível' if !@sale_post.enabled? && @sale_post.user != current_user
  end
end

app/helpers/sale_posts_helper.rb
module SalePostsHelper
  def cover_image(post, classes: '')
    return image_tag post.cover, alt: "#{post.title} foto", class: classes if post.cover.attached?

    image_tag 'no-image.jpg', alt: 'Anúncio sem foto', class: classes
  end

  def enable_disable_button(post)
    classes = 'bg-gray-400 hover:bg-gray-300 p-1 rounded text-red-800'
    return link_to 'Desativar anúncio', disable_sale_post_path(post), method: :post, class: classes if post.enabled?

    link_to 'Reativar anúncio', enable_sale_post_path(post), method: :post, class: classes
  end
end

app/views/sale_posts/_comment-item.html.erb
<div class="comment-item text-sm mb-4">
  <header class="comment-header">
    <% unless author %>
      <%= link_to comment.user.name, profile_user_path(comment.user), class: "font-bold" %>
      <span class="text-xs text-gray-800"><%= comment.user.department %></span>
    <% else %>
      <%= link_to author.name, profile_user_path(author), class: "font-bold" %>
      <span class="text-xs text-gray-800"><%= author.department %></span>
    <% end %>
  </header>
  <p class="comment-body">
    <%= comment.body %>
    <span class="text-xs text-gray-600 ml-1"><%= l comment.created_at, format: :short %></span>
  </p>
</div>

app/views/sale_posts/_form.html.erb
<% sale_post.errors.full_messages.each do |message| %>
  <p class="border border-red-700 text-red-700 mb-1 px-2 py-1"><%= message %></p>
<% end %>

<%= form_with model: sale_post, local: true, class: "flex flex-col" do |f| %>
  <div class="flex">
    <div class="flex flex-col">
      <%= f.label :cover, class: "text-sm text-gray-700 mt-3" %>
      <%= f.file_field :cover, placeholder: 'Email', class: "p-1 border border-gray-400 rounded text-sm w-64" %>
    </div>
    <div class="flex flex-col ml-4">
      <%= f.label :category_id, class: "text-sm text-gray-700 mt-3" %>
      <%= f.collection_select :category_id, @categories, :id, :name, {prompt: 'Escolha uma categoria'}, {class: "p-2 border border-gray-400 bg-white rounded text-sm w-64"} %>
    </div>
  </div>
  <%= f.label :title, class: "text-sm text-gray-700 mt-3" %>
  <%= f.text_field :title, placeholder: 'Título', class: "p-2 border border-gray-400 rounded text-sm" %>
  <%= f.label :description, class: "text-sm text-gray-700 mt-3" %>
  <%= f.text_area :description, placeholder: 'Descrição', class: "p-2 border border-gray-400 rounded text-sm" %>
  <%= f.label :price, class: "text-sm text-gray-700 mt-3" %>
  <%= f.number_field :price, placeholder: 'Valor (número inteiro)', class: "p-2 border border-gray-400 rounded text-sm" %>
  
  <%= f.submit sale_post.persisted? ? 'Atualizar anúncio' : 'Criar anúncio', class: "mt-8 mb-4 py-2 bg-gray-900 text-white hover:bg-gray-800 cursor-pointer" %>
<% end %>

app/views/sale_posts/edit.html.erb
<section class="edit-post-container">
  <h1 class="text-2xl font-bold mb-2">Editar anúncio</h1>

  <%= render partial: 'form', locals: { sale_post: @sale_post } %>
</section>

app/views/sale_posts/new.html.erb
<section class="new-post-container">
  <h1 class="text-2xl font-bold mb-2">Novo anúncio</h1>

  <%= render partial: 'form', locals: { sale_post: @sale_post } %>
</section>

app/views/sale_posts/search.html.erb
<h1 class="text-xl font-bold text-gray-900">Resultados da busca por: <u><%= @keyword %></u></h1>
<em class="mb-4 block">Total de anúncios encontrados: <%= @posts.size %></em>
<%= render partial: 'shared/sale_post_list', locals: { posts: @posts } %>

app/views/sale_posts/show.html.erb
<section class="post-container text-gray-900 grid sm:grid-cols-1 lg:grid-cols-2 mb-12">
  <div class="post-details flex flex-col">
    <h1 class="text-2xl font-bold mb-2">
      <%= @sale_post.title %>
    </h1>
    <p class="post-author text-gray-600 text-sm mb-2">
      <span>Anunciado por: </span>
      <%= link_to @sale_post.user.name, profile_user_path(@sale_post.user), class: "underline" %> 
      em <%= l @sale_post.created_at, format: :short %>
    </p>
  
    <div class="mb-2">
      <%= simple_format(h(@sale_post.description)) %>
    </div>
    <p class="text-sm mb-4">
      <span >Categoria: </span>
      <%= link_to @sale_post.category.name, @sale_post.category, class: "underline" %>
    </p>
    <div class="buy-price mt-auto mb-4">
      <div class="text-3xl mb-4"><%= number_to_currency @sale_post.price %></div>
  
      <% if current_user == @sale_post.user && !@sale_post.sold? %>
        <div class="seller-controllers flex items-center">
          <%= enable_disable_button(@sale_post) %>
          <%= link_to 'Editar', edit_sale_post_path(@sale_post), class: 'ml-4 text-sm underline' %>
          <%= link_to 'Excluir', @sale_post, method: :delete, class: 'ml-4 text-sm underline' %>
        </div>
      <% end %>

      <% if @sale_post.sold? %>
        <p class="text-sm">Anúncio finalizado</p>
      <% end %>
  
      <% if current_user.enabled? && current_user != @sale_post.user %>
        <div class="">
          <% if @order_in_progress.present? %>
            <%= link_to "Ver pedido", @order_in_progress, class: "bg-blue-700 hover:bg-blue-600 text-white p-2 rounded" %>
          <% else %>
            <%= link_to "Comprar", sale_post_orders_path(@sale_post.id), method: :post, data: { disable_with: "Aguarde" }, class: "bg-green-700 hover:bg-green-600 text-white p-2 rounded" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="image-container bg-gray-300 flex justify-center w-full h-screen/2">
    <%= cover_image(@sale_post, classes: "max-w-4xl object-contain") %>
  </div>
</section>

<div class="questions-container">
  <h2 class="text-xl font-bold mb-2">Perguntas e Respostas</h2>

  <% if @questions.empty? %>
    <p class="mb-2 italic text-sm">Não há perguntas até o momento.</p>
  <% end %>

  <% @questions.each do |question| %>
    <div data-question="<%= question.id %>">
      <%= render partial: 'comment-item', locals: { comment: question, author: false } %>
      <% if question.answer %>
        <div class="pl-12">
          <%= render partial: 'comment-item', locals: { comment: question.answer, author: @sale_post.user } %>
        </div>
      <% else %>
        <% if current_user == @sale_post.user %>
          <%= form_with model: [@sale_post, question, @answer], local: true, class: "answer-form w-full"  do |f| %>
            <%= f.text_area :body, placeholder: 'Escreva uma resposta...', class: "p-2 border border-gray-400 rounded text-sm block w-full" %>
            <div class="text-right">
              <%= f.submit 'Enviar', class: "bg-gray-900 text-white text-sm px-2 cursor-pointer hover:bg-gray-800" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% unless current_user == @sale_post.user %>
    <%= form_with model: [@sale_post, @question], local: true, class: "question-form w-full"  do |f| %>
      <%= f.text_area :body, placeholder: 'Escreva uma pergunta...', class: "p-2 border border-gray-400 rounded text-sm block w-full" %>
      <div class="text-right">
        <%= f.submit 'Enviar', class: "bg-gray-900 text-white text-sm px-2 cursor-pointer hover:bg-gray-800" %>
      </div>
    <% end %>
  <% end %>
</div>