config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [] do
    get 'profile', on: :member
  end
  resources :sale_posts, only: [:show, :new, :create, :edit, :destroy, :update] do
    resources :orders, only: [:create]
    resources :questions, only: [:create] do
      resources :answers, only: [:create]
    end
    post 'disable', on: :member
    post 'enable', on: :member
    get 'search', on: :collection
  end
  resources :categories, only: [:show]
  resources :orders, only: [:show] do
    resources :messages, only: [:create]
    member do
      post 'complete'
      post 'cancel'
    end
  end
  resources :notifications, only: [] do
    post 'seen'
  end
  resource :my_account, controller: :my_account, only: [:show] do
    get :history, on: :member
    get :sale_posts, on: :member
  end
  resource :dashboard, controller: :dashboard, only: [:show] do
    resources :companies, only: [:show, :new, :create] do
      resources :categories, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :company, only: [] do
        resources :sale_posts, only: [:index]
      end
    end
  end

  root to: 'home#index'
end

app/views/shared/_footer.html.erb
<footer class="container mx-auto text-center my-4 text-gray-600 text-sm">
  <p>Copyright © 2020 Felipe Rosa</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-900 text-white flex items-center justify-between px-2 md:px-4 lg:px-8 py-2 min-w-0">
  <div class="flex-1 flex items-center">
    <%= link_to root_path, class: "w-24 md:w-32" do %>
      <%= image_tag "logo-white.png" %>
    <% end %>
    <%= form_with url: search_sale_posts_path, method: :get, local: true, class: "ml-2 md:ml-4 flex-1 flex items-center justify-center" do |f| %>
      <%= f.text_field :q, placeholder: 'Buscar', class: "w-0 px-2 flex-1 text-gray-900 text-sm h-8 " %>
      <%= button_tag type: 'submit', class: "search-btn px-2 bg-gray-200 text-gray-900 text-sm h-8" do %>
        <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
            viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
            width="512px" height="512px">
            <path
              d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
        </svg>
      <% end %>
    <% end %>
  </div>

  <div class="w-8 h-8 ml-3 flex-shrink-0 block md:hidden">
    <button class="nav-btn flex items-center justify-center w-full h-full border text-gray-400 border-gray-700 rounded hover:text-white hover:border-white">
      <svg class="fill-current h-4 w-4" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  
  <div class="user-menu items-center justify-between ml-8 md:text-sm hidden md:flex">
    <%= link_to "Criar um anúncio", new_sale_post_path, class: "mr-8 border border-gray-200 text-gray-200 hover:bg-gray-200 hover:text-gray-900 rounded px-3 py-1" if current_user.enabled? %>
    <div>
      <%= link_to my_account_path, class: "hover:underline" do %>
        <%= show_user_title %>
        <% if current_user.notifications.unseen.present? %>
          <span class="notifications rounded-full bg-red-600 text-white inline-block text-sm text-center w-5 h-5">
            <%= current_user.notifications.unseen.size %>
          </span>
        <% end %>
      <% end %>
      <span class="mx-2">|</span>
      <%= link_to "Sair", destroy_user_session_path, class: "hover:underline", method: :delete %>
    </div>
  </div>

  <ul class="nav-menu absolute top-0 right-0 bg-gray-900 text-sm p-4 mt-12 hidden md:hidden z-10">
    <li class="border-b pb-2">
      <%= link_to "Criar um anúncio", new_sale_post_path, class: "hover:underline" if current_user.enabled? %>
    </li>
    <li class="pt-2">
      <%= link_to my_account_path, class: "hover:underline" do %>
        <%= show_user_title %>
        <% if current_user.notifications.unseen.present? %>
          <span class="notifications rounded-full bg-red-600 text-white inline-block text-sm text-center w-5 h-5">
            <%= current_user.notifications.unseen.size %>
          </span>
        <% end %>
      <% end %>
    </li>
    <li class="">
      <%= link_to "Sair", destroy_user_session_path, class: "hover:underline", method: :delete %>
    </li>
  </ul>

</nav>

<% unless current_user.enabled? %>
  <div class="fill-profile-warning text-center bg-yellow-200">
    <p>
      Seu perfil está incompleto. Para comprar ou vender, 
      <%= link_to 'preencha seu perfil', edit_user_registration_path, class: "text-blue-500"%>.
    </p>
  </div>
<% end %>

<%= javascript_pack_tag 'navbar_toggle' %>

app/views/shared/_sale_post_item.html.erb
<%= link_to sale_post_path(post.id), class: "post-item", data: { item: post.id }, title: post.title do %>
  <article class="rounded overflow-hidden shadow hover:bg-gray-100  transform hover:scale-105 lg:hover:scale-110 transition-transform duration-500 ease-in-out">
    <%= cover_image(post, classes: "w-full h-48 object-cover") %>

    <div class="px-4 py-2 relative h-40 flex flex-col">
      <span class="absolute bg-gray-900 text-white border-t border-l font-bold inline-block top-0 right-0 -my-4 py-1 px-2"><%= number_to_currency post.price %></span>
      <span class="inline-block text-xs text-gray-700 mr-2 mb-1"><%= post.category.name %></span>

      <h2 class="font-bold text-md mb-1 truncate h-14"><%= post.title %></h2>
      <p class="truncate-3-lines text-sm"><%= post.description %></p>
      <p class="date text-xs text-gray-600 mt-auto text-right"><%= l post.created_at, format: :short %></p>
    </div>
  </article>
<% end %>

app/views/shared/_sale_post_list.html.erb
<ul class="grid gap-4 lg:gap-8 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
  <% posts.each do |post| %>
    <li><%= render partial: 'shared/sale_post_item', locals: { post: post } %></li>
  <% end %>
</ul>