config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [] do
    get 'profile', on: :member
  end
  resources :sale_posts, only: [:show, :new, :create, :edit, :destroy, :update] do
    resources :orders, only: [:create]
    resources :questions, only: [:create] do
      resources :answers, only: [:create]
    end
    post 'disable', on: :member
    post 'enable', on: :member
    get 'search', on: :collection
  end
  resources :categories, only: [:show]
  resources :orders, only: [:show] do
    resources :messages, only: [:create]
    member do
      post 'complete'
      post 'cancel'
    end
  end
  resources :notifications, only: [] do
    post 'seen'
  end
  resource :my_account, controller: :my_account, only: [:show] do
    get :history, on: :member
    get :sale_posts, on: :member
  end
  resource :dashboard, controller: :dashboard, only: [:show] do
    resources :companies, only: [:show, :new, :create] do
      resources :categories, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :company, only: [] do
        resources :sale_posts, only: [:index]
      end
    end
  end

  root to: 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :sale_post
  belongs_to :buyer, class_name: 'User'
  belongs_to :seller, class_name: 'User'
  has_many :messages

  validates_uniqueness_of :sale_post, scope: :buyer, conditions: -> { where(status: :in_progress) }

  before_validation :assign_seller_with_sale_post_user, on: :create
  after_create :send_notification

  enum status: { in_progress: 0, completed: 10, canceled: 20 }

  private

  def assign_seller_with_sale_post_user
    self.seller = sale_post.user
  end

  def send_notification
    sale_post.user.notifications.create(body: "Solicitação de compra pendente em anúncio #{sale_post.title}",
                                        path: "/orders/#{id}")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :must_be_buyer_or_seller, only: [:show]
  before_action :must_be_seller, only: [:complete, :cancel]

  def create
    @sale_post = SalePost.find(params[:sale_post_id])
    @order = Order.new(item_name: @sale_post.title, item_description: @sale_post.description, sale_post: @sale_post,
                       posted_price: @sale_post.price, status: :in_progress, buyer: current_user)
    if @order.save
      redirect_to order_path(@order), notice: 'Solicitação de compra enviada. '\
                                                                      'Aguarde aprovação do vendedor'
    else
      redirect_back fallback_location: root_path, alert: 'Erro ao solicitar compra. Tente novamente mais tarde'
    end
  end

  def show
    @message = Message.new
    @messages = @order.messages.includes([:author])
  end

  def complete
    final_price = params[:final_price]
    order_final_price = final_price.present? ? final_price : @order.posted_price
    @order.update(status: :completed, final_price: order_final_price)
    @order.sale_post.sold!
    @order.buyer.notifications.create(
      body: "O vendedor aceitou seu pedido de compra para '#{@order.item_name}'", path: order_path(@order)
    )
    redirect_to @order, notice: 'Venda finalizada com sucesso'
  end

  def cancel
    @order.canceled!
    @order.buyer.notifications.create(
      body: "O vendedor cancelou seu pedido de compra para '#{@order.item_name}'", path: order_path(@order)
    )
    redirect_to root_path, notice: 'Venda cancelada com sucesso'
  end

  private

  def must_be_seller
    @order = Order.find(params[:id])
    return redirect_to root_path if current_user != @order.seller
  end

  def must_be_buyer_or_seller
    @order = Order.find(params[:id])
    redirect_to root_path unless current_user == @order.buyer || current_user == @order.seller
  end
end

app/views/orders/_message.html.erb
<div class="message-item text-sm mb-4">
  <header class="message-header">
    <%= link_to message.author.name, profile_user_path(message.author), class: "font-bold" %>
    <span class="text-xs text-gray-800"><%= message.author.department %></span>
  </header>
  <p class="message-body">
    <%= message.body %>
    <span class="text-xs text-gray-600 ml-1"><%= l message.created_at, format: :short %></span>
  </p>
</div>

app/views/orders/show.html.erb
<section class="order-container">
  <div class="order text-gray-900 mb-12">
    <div class="order-details flex flex-col">
      <h1 class="text-2xl font-bold mb-2">
        <span class="font-normal">Pedido:</span> <%= Order.human_attribute_name("status.#{@order.status}") %>
      </h1>
      <p class="font-bold text-lg mb-1">
        <%= @order.item_name %>
      </p>
    
      <div class="text-sm">
        <%= simple_format(h(@order.item_description)) %>
      </div>

      <p class="mb-8 text-sm">
        <%= link_to 'Ver anúncio', @order.sale_post, class: 'underline hover:no-underline' if @order.in_progress? %>
      </p>

      <div class="text-sm">
        <p>
          <span class="text-xs">Vendedor: </span>
          <%= link_to @order.seller.name, profile_user_path(@order.seller), class: 'underline hover:no-underline' %>
        </p>
        <p>
          <span class="text-xs">Comprador: </span>
          <%= link_to @order.buyer.name, profile_user_path(@order.buyer), class: 'underline hover:no-underline' %>
          <%=  %>
        </p>
      </div>

      <div class="mt-8 mb-4">
        <div class="text-lg">
          <p>
            <span class="text-sm">Valor anunciado: </span>
            <%= number_to_currency @order.posted_price %>
          </p>
          
          <% if @order.completed? %>
            <p>
              <span class="text-sm">Valor final: </span>
              <span class="font-medium"><%= number_to_currency @order.final_price %></span>
            </p>
          <% end %>
        </div>
        <% if current_user == @order.seller && @order.in_progress? %>
          <div class="seller-controllers mt-4">
            <button class="complete-btn bg-green-600 hover:bg-green-500 text-white rounded mr-2 py-1 px-2">Concluir venda</button>
            <%= link_to 'Cancelar venda', cancel_order_path, method: :post, class: "bg-red-600 hover:bg-red-500 rounded text-white inline-block py-1 px-2" %>
          </div>
          <%= form_with url: complete_order_path, local: true, class: "complete-form hidden mt-4" do |f| %>
            <%= f.number_field :final_price, placeholder: "Valor final", class: "p-2 border border-gray-400 rounded w-48 text-sm" %>
            <%= f.submit 'Finalizar', class: "p-2 border bg-gray-900 text-white rounded text-sm" %>
          <% end %>
          <%= javascript_pack_tag 'seller_actions_on_order' %>
        <% end %>
      </div>
    </div>
  </div>


  <% if @order.in_progress? %>
    <div class="messages-container">
      <h2 class="text-xl font-bold mb-2">Mensagens</h2>
      <p class="text-sm mb-2">
        <%= 'Não há mensagens' if @messages.empty? %>
      </p>
      <% @messages.each do |message| %>
        <%= render partial: 'message', locals: { message: message } %>
      <% end %>
      <%= form_with model: [@order, @message], local: true, class: "sm:w-full lg:w-2/3" do |f| %>
        <%= f.text_area :body, placeholder: 'Escreva uma mensagem...', class: "p-2 border border-gray-400 rounded text-sm block w-full" %>
        <div class="text-right">
          <%= f.submit 'Enviar', class: "bg-gray-900 text-white text-sm px-2 cursor-pointer hover:bg-gray-800" %>
        </div>
      <% end %>
    </div>
  <% end %>
</section>