config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [] do
    get 'profile', on: :member
  end
  resources :sale_posts, only: [:show, :new, :create, :edit, :destroy, :update] do
    resources :orders, only: [:create]
    resources :questions, only: [:create] do
      resources :answers, only: [:create]
    end
    post 'disable', on: :member
    post 'enable', on: :member
    get 'search', on: :collection
  end
  resources :categories, only: [:show]
  resources :orders, only: [:show] do
    resources :messages, only: [:create]
    member do
      post 'complete'
      post 'cancel'
    end
  end
  resources :notifications, only: [] do
    post 'seen'
  end
  resource :my_account, controller: :my_account, only: [:show] do
    get :history, on: :member
    get :sale_posts, on: :member
  end
  resource :dashboard, controller: :dashboard, only: [:show] do
    resources :companies, only: [:show, :new, :create] do
      resources :categories, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :company, only: [] do
        resources :sale_posts, only: [:index]
      end
    end
  end

  root to: 'home#index'
end

app/controllers/my_account_controller.rb
class MyAccountController < ApplicationController
  def show
    @user = current_user
    @notifications_unseen = @user.notifications.unseen.order(created_at: :desc)
    @sale_orders = current_user.sale_orders.in_progress.includes([:buyer])
    @buy_orders = current_user.buy_orders.in_progress.includes([:seller, :buyer])
  end

  def history
    @sale_orders = current_user.sale_orders.where.not(status: :in_progress).includes([:buyer])
    @buy_orders = current_user.buy_orders.where.not(status: :in_progress).includes([:seller, :buyer])
  end

  def sale_posts
    @posts = current_user.sale_posts.with_attached_cover.includes([:category])
  end
end

app/views/my_account/_account-nav.html.erb
<nav class="text-gray-800 mb-6 pb-6 border-b">
  <ul class="flex flex-col md:flex-row items-center justify-center">
    <li class="px-6 <%= current_page?(my_account_path) ? 'font-bold border-b-2' : 'underline hover:no-underline' %>">
      <%= link_to_unless_current 'Minha conta', my_account_path %>
    </li>
    <li class="px-6 <%= current_page?(sale_posts_my_account_path) ? 'font-bold border-b-2' : 'underline hover:no-underline' %>">
      <%= link_to_unless_current 'Meus anúncios', sale_posts_my_account_path %>
    </li>
    <li class="px-6 <%= current_page?(history_my_account_path) ? 'font-bold border-b-2' : 'underline hover:no-underline' %>">
      <%= link_to_unless_current 'Meu histórico', history_my_account_path %>
    </li>
    <li class="px-6 <%= current_page?(profile_user_path(current_user)) ? 'font-bold border-b-2' : 'underline hover:no-underline' %>">
      <%= link_to_unless_current 'Meu perfil', profile_user_path(current_user) %>
    </li>
  </ul>
</nav>

app/views/my_account/_notifications.html.erb
<div class="notifications-unseen mb-4">
  <h2 class="text-lg font-bold mb-2">Notificações não lidas (<%= @user.notifications.unseen.size %>)</h2>
  <% if notifications.empty? %>
    <p class="text-sm">Não há notificações não lidas a serem exibidas</p>
  <% end %>
  <ul>
    <% notifications.each do |notification| %>
      <li class="text-gray-800 text-sm">
        <%= link_to notification_seen_path(notification), method: :post, class: 'bg-gray-200 hover:bg-gray-300 mb-2 p-2 flex flex-wrap justify-between' do %>
          <span><%= notification.body %></span>
          <span class="text-xs"><%= l notification.created_at, format: :short %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/my_account/_orders-list.html.erb
<ul class="orders-list flex flex-wrap gap-2">
  <% if orders.empty? %>
    <p class="text-sm">Sem negociações a serem exibidas.</p>
  <% end %>
  <% orders.each do |order| %>
    <%= link_to order, title: order.item_name do %>
      <li class="orders-item border p-4 hover:bg-gray-100 flex items-center">
        <div class="mr-2">
          <p class="font-bold text-sm"><%= order.item_name %></p>
          <span class="text-xs">
            <%= current_user == order.buyer ? order.seller.name : order.buyer.name %>
          </span>
        </div>
        <% unless order.in_progress? %>
            <% if order.completed? %>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="text-green-600 w-10 h-10"> 
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
              </svg>
            <% else %>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="text-red-600 w-10 h-10">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
              </svg>
            <% end %>
        <% end %>
      </li>
    <% end %>

  <% end %>
</ul>

app/views/my_account/history.html.erb
<%= render 'account-nav' %>

<section class="orders-container">
  <h1 class="text-xl font-bold mb-2">Meus histórico</h1>
  <section class="buy-orders mb-4">
    <h2 class="text-lg font-bold mb-1">Histórico de compras</h2>
    <%= render partial: 'orders-list', locals: { orders: @buy_orders } %>
  </section>

  <section class="sale-orders">
    <h2 class="text-lg font-bold mb-1">Histórico de vendas</h2>
    <%= render partial: 'orders-list', locals: { orders: @sale_orders } %>
  </section>
</section>

app/views/my_account/sale_posts.html.erb
<%= render 'account-nav' %>

<section class="my-posts-container">
  <h1 class="text-xl font-bold mb-2">Meus anúncios</h1>
  <%= render partial: 'shared/sale_post_list', locals: { posts: @posts } %>
</section>

app/views/my_account/show.html.erb
<%= render 'account-nav' %>

<section class="profile-container text-gray-900">
  <%= render partial: 'notifications', locals: { notifications: @notifications_unseen } %>

  <div class="my-orders-in-progress">
    <h2 class="text-lg font-bold mb-2">Negociações em andamento</h2>
    <% if @buy_orders.present? %>
      <div class="buy-orders px-2 mb-4">
        <h3 class="font-bold mb-1">Compra:</h3>
        <%= render partial: 'orders-list', locals: { orders: @buy_orders } %>
      </div>
    <% end %>

    <% if @sale_orders.present? %>
      <div class="sale-orders px-2">
        <h3 class="font-bold mb-1">Venda:</h3>
        <%= render partial: 'orders-list', locals: { orders: @sale_orders } %>
      </div>
    <% end %>
  </div>
</section>